version: '3'

services:
  api:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/api

  db:
    image: mysql
    ports:
      - '3306:3306'
    env_file:
      - .env.local
