version: '3'

services:
  api:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/api
    env_file:
      - .env.example
    environment:
      - MYSQL_HOST=db

  db:
    image: mysql
    ports:
      - '3306:3306'
    env_file:
      - .env.example
    environment:
      - MYSQL_HOST=db
